# Comparisson between implementations

In [19]:
import os
os.chdir('..')

import time
import numpy as np

from scripts.defineProblem import build_vectors
from scripts.tensorialSolution import iter_policy_evaluation,iter_policy_evaluation_low,iter_policy_evaluation_conv,iter_policy_evaluation_lowconv,value_iteration

from scripts.classicImplementation import GridWorld,policy_evaluation

from scripts.librarySolution import build_environment
import mdptoolbox

In [2]:
simulations=500

## Classic implementation

In [3]:
iters=1000
env = GridWorld(4)

In [4]:
s = time.time()
value_table = policy_evaluation(env, steps=iters, in_place=False)
print(value_table)
print((time.time() - s) * 1e3, "ms")

[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
151.40604972839355 ms


In [5]:
import timeit

In [6]:
def run_vi():
    value_table = policy_evaluation(env, steps=iters, in_place=False)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

100.86562799988315 ms


## Library implementation

In [22]:
R,P=build_environment()

In [23]:
s = timeit.default_timer()
vi = mdptoolbox.mdp.ValueIteration(P, R, 0.99, epsilon=1e-6, max_iter=iters)
vi.run()
print(vi.policy)
print((timeit.default_timer() - s) * 1e3, "ms")

(0, 3, 3, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 2, 2)
1.44009999348782 ms


In [9]:
def run_vi():
    vi = mdptoolbox.mdp.ValueIteration(P, R, 0.99, epsilon=1e-6, max_iter=iters)
    vi.run()

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

0.24881799996364865 ms


## Tensor implementation

In [24]:
V_0,R,PI,P,P_low=build_vectors()

In [25]:
s = time.time()
V_i=iter_policy_evaluation(V_0,R,PI,P,1,iters)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0. -14. -20. -22. -14. -18. -20. -20. -20. -20. -18. -14. -22. -20.
 -14.]
24.005413055419922 ms


In [12]:
def run_vi():
    V_i=iter_policy_evaluation(V_0,R,PI,P,1,iters)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

18.856110000051558 ms


## Tensor optimized implementation

In [13]:
s = time.time()
V_i=iter_policy_evaluation_low(V_0,R,PI,P_low,1,iters)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0. -14. -20. -22. -14. -18. -20. -20. -20. -20. -18. -14. -22. -20.
 -14.]
4.4231414794921875 ms


In [14]:
def run_vi():
    V_i=iter_policy_evaluation_low(V_0,R,PI,P_low,1,iters)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

8.942055999941658 ms


## Tensor with convergency criteria implementation

In [15]:
s = time.time()
V_i=iter_policy_evaluation_conv(V_0,R,PI,P,.99,iters,1e-6)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0.         -11.94519721 -16.96107865 -18.60541196 -11.94519721
 -15.31674535 -16.97752209 -16.96107865 -16.96107865 -16.97752209
 -15.31674535 -11.94519721 -18.60541196 -16.96107865 -11.94519721]
8.372783660888672 ms


In [16]:
def run_vi():
    V_i=iter_policy_evaluation_conv(V_0,R,PI,P,.99,iters,1e-6)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

5.9740480000618845 ms


## Tensor optimized with convergency criteria implementation

In [17]:
s = time.time()
V_i=iter_policy_evaluation_lowconv(V_0,R,PI,P_low,.99,iters,1e-6)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0.         -11.94520573 -16.96109128 -18.60542609 -11.94520573
 -15.31675647 -16.97753463 -16.96109128 -16.96109128 -16.97753463
 -15.31675647 -11.94520573 -18.60542609 -16.96109128 -11.94520573]
15.546321868896484 ms


In [18]:
def run_vi():
    V_i=iter_policy_evaluation_lowconv(V_0,R,PI,P_low,.99,iters,1e-6)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

5.2191200002562255 ms


## Tensor Value Iteration

In [ ]:
s = time.time()
pi_star=value_iteration(R,P,0.99,iters,1e-3)
print(pi_star)
print((time.time() - s) * 1e3, "ms")

[0 3 3 1 0 0 0 1 0 0 1 1 0 2 2]
0.0 ms


In [ ]:
def run_vi():
    pi_star=value_iteration(R,P,0.99,iters,1e-3)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

0.10475999995833263 ms
