# Comparisson between implementations

In [1]:
import os
os.chdir('..')

import time
import numpy as np

from scripts.defineProblem import build_vectors
from scripts.tensorialSolution import iter_policy_evaluation,iter_policy_evaluation_low,iter_policy_evaluation_conv,iter_policy_evaluation_lowconv

from scripts.classicImplementation import GridWorld,policy_evaluation

from scripts.librarySolution import build_environment
import mdptoolbox

In [2]:
simulations=500

## Classic implementation

In [6]:
iters=1000
env = GridWorld(4)

In [100]:
s = time.time()
value_table = policy_evaluation(env, steps=iters, in_place=False)
print(value_table)
print((time.time() - s) * 1e3, "ms")

[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
72.89314270019531 ms


In [4]:
import timeit

In [ ]:
def run_vi():
    value_table = policy_evaluation(env, steps=iters, in_place=False)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

57.379991998896 ms


## Library implementation

In [15]:
R,P=build_environment()

In [132]:
s = timeit.default_timer()
vi = mdptoolbox.mdp.ValueIteration(P, R, 0.99, epsilon=1e-6, max_iter=iters)
vi.run()
print(vi.V)
print((timeit.default_timer() - s) * 1e3, "ms")

(0.0, -1.0, -1.99, -2.9701, -1.0, -1.99, -2.9701, -1.99, -1.99, -2.9701, -1.99, -1.0, -2.9701, -1.99, -1.0)
0.6733000045642257 ms


In [17]:
def run_vi():
    vi = mdptoolbox.mdp.ValueIteration(P, R, 0.99, epsilon=1e-6, max_iter=iters)
    vi.run()

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

0.16608400037512183 ms


## Tensor implementation

In [2]:
V_0,R,PI,P,P_low=build_vectors()

In [35]:
s = time.time()
V_i=iter_policy_evaluation(V_0,R,PI,P,1,iters)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0. -14. -20. -22. -14. -18. -20. -20. -20. -20. -18. -14. -22. -20.
 -14.]
16.5255069732666 ms


In [19]:
def run_vi():
    V_i=iter_policy_evaluation(V_0,R,PI,P,1,iters)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

9.66513599967584 ms


## Tensor optimized implementation

In [36]:
s = time.time()
V_i=iter_policy_evaluation_low(V_0,R,PI,P_low,1,iters)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0. -14. -20. -22. -14. -18. -20. -20. -20. -20. -18. -14. -22. -20.
 -14.]
7.226228713989258 ms


In [20]:
def run_vi():
    V_i=iter_policy_evaluation_low(V_0,R,PI,P_low,1,iters)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

5.01678999979049 ms


## Tensor with convergency criteria implementation

In [30]:
s = time.time()
V_i=iter_policy_evaluation_conv(V_0,R,PI,P,.99,iters,1e-6)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0.         -11.94519721 -16.96107865 -18.60541196 -11.94519721
 -15.31674535 -16.97752209 -16.96107865 -16.96107865 -16.97752209
 -15.31674535 -11.94519721 -18.60541196 -16.96107865 -11.94519721]
4.382133483886719 ms


In [21]:
def run_vi():
    V_i=iter_policy_evaluation_conv(V_0,R,PI,P,.99,iters,1e-6)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

2.8047039988450706 ms


## Tensor optimized with convergency criteria implementation

In [8]:
s = time.time()
V_i=iter_policy_evaluation_lowconv(V_0,R,PI,P_low,.99,iters,1e-6)
print(V_i)
print((time.time() - s) * 1e3, "ms")

[  0.         -11.94520573 -16.96109128 -18.60542609 -11.94520573
 -15.31675647 -16.97753463 -16.96109128 -16.96109128 -16.97753463
 -15.31675647 -11.94520573 -18.60542609 -16.96109128 -11.94520573]
4.00853157043457 ms


In [ ]:
def run_vi():
    V_i=iter_policy_evaluation_lowconv(V_0,R,PI,P_low,.99,iters,1e-6)

t = timeit.repeat(run_vi, repeat=10, number=50)

print(min(t) / 50 * 1e3, "ms")

2.472804000135511 ms
