# Gridworld Environment Problem

## Problem explanation

Solution of following problem is implemented using method proposed, "Tensorial Iterative Policy Evaluation". Problem is taken from Example 4.1, Chapter 4 Dynamic Programming of "Reinforcement Learning, An Introduction" book; there it is carefully described.

![Example 4.1](../figures/figure1.png){width=600}

### Initial Policy

![Initial Policy](../figures/figure3.png){width=600}

### Optimal Policy

![Optimal Policy](../figures/figure4.png){width=600}

## Implementation scripts

In [ ]:
import os
os.chdir('..')

import numpy as np

from scripts.defineProblem import build_vectors
from scripts.tensorialSolution import iter_policy_evaluation

## Specific tensors for the problem

In [2]:
V_0,R,PI,P=build_vectors()

### Initial state value vector 

In [9]:
print(V_0.shape)
V_0

(15,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Reward vector

In [10]:
print(R.shape)
R

(15,)


array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

### Actions probabilities vector

In [11]:
print(PI.shape)
PI

(4,)


array([0.25, 0.25, 0.25, 0.25])

### Transition matrices tensor

In [8]:
print(P.shape)
print(P)

(4, 15, 15)
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 

## Examples of iterations

Here are done by hand the first iterations, which are as the results of the book. Book results are truncated by one decimal.

![First Iterations](../figures/figure5.png){width=600}

### First iteration example

In [12]:
RV=R+V_0
RV

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1.])

In [14]:
RVP=np.tensordot(P,RV,axes=1)
RVP

array([[ 0., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1.],
       [ 0., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1.],
       [ 0., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1.],
       [ 0., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1.]])

In [15]:
V_1=PI @ RVP 
V_1

array([ 0., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1.])

### Second iteration example

In [16]:
V_2=PI @ np.tensordot(P,R+V_1,axes=1)
V_2

array([ 0.  , -1.75, -2.  , -2.  , -1.75, -2.  , -2.  , -2.  , -2.  ,
       -2.  , -2.  , -1.75, -2.  , -2.  , -1.75])

## Tensorial iterative policy evaluation

Finally, it is applied to get the optimal.

![First Iterations](../figures/figure4.png){width=600}

In [25]:
gamma=1

### $k=3$ iterations

In [26]:
iterations=3

V_i=iter_policy_evaluation(V_0,R,PI,P,gamma,iterations)
V_i

array([ 0.    , -2.4375, -2.9375, -3.    , -2.4375, -2.875 , -3.    ,
       -2.9375, -2.9375, -3.    , -2.875 , -2.4375, -3.    , -2.9375,
       -2.4375])

### $k=10$ iterations

In [27]:
iterations=10

V_i=iter_policy_evaluation(V_0,R,PI,P,gamma,iterations)
V_i

array([ 0.        , -6.13796997, -8.35235596, -8.96731567, -6.13796997,
       -7.73739624, -8.42782593, -8.35235596, -8.35235596, -8.42782593,
       -7.73739624, -6.13796997, -8.96731567, -8.35235596, -6.13796997])

### $k=\infty$ iterations

In [ ]:
iterations=500

V_i=iter_policy_evaluation(V_0,R,PI,P,gamma,iterations)
V_i

array([  0., -14., -20., -22., -14., -18., -20., -20., -20., -20., -18.,
       -14., -22., -20., -14.])

Results shows the huge usability of the method, getting exact results with less procedures.